import type { Metadata } from 'next';
import './../globals.css';
import StoreProvider from '@/components/StoreProvider';
import LandingLayout from '@/components/layout/LandingLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <main>
          <StoreProvider>
            <LandingLayout locale={locale}>{children}</LandingLayout>
          </StoreProvider>
        </main>
      </body>
    </html>
  );
}
