import type { Metadata } from 'next';
import './../globals.css';
import initTranslations from '../../i18n';
import TranslationsProvider from '@/components/TranslationsProvider';
import DashboardLayout from '@/components/layout/DashboardLayout';
import StoreProvider from '@/components/StoreProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const i18Namespaces = ['home', 'common'];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  const { resources } = await initTranslations(locale, i18Namespaces);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <main>
          <TranslationsProvider locale={locale} namespaces={i18Namespaces} resources={resources}>
            <StoreProvider>
              <DashboardLayout locale={locale}>{children}</DashboardLayout>
            </StoreProvider>
          </TranslationsProvider>
        </main>
      </body>
    </html>
  );
}
